name: On Push

on:
  push:
    branches:
      - main
  workflow_call:
  workflow_dispatch:

jobs:
  ci:
    uses: ./.github/workflows/ci.yml

  check_package_name:
    needs:
      - ci
    uses: ./.github/workflows/check_package_name.yml

  cd:
    needs:
      - ci
      - check_package_name
    if: needs.check_package_name.outputs.package_name != '"npm-package-template"'
    uses: ./.github/workflows/cd.yml
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
